server.port=8081
spring.application.name=ebook-backend
logging.level.org.springframework.web=DEBUG

# Allow large file uploads (for videos)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
